# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg, json]

      - id: end-of-file-fixer
        exclude_types: [svg, json]

      - id: check-yaml
        exclude: group_vars/all.yml|csv-playbook-example/inventory.yml|avd/global_vars/HOME_LAB_CVAAS.yml|DEMO_CVAAS.yml|ansible/playbooks/all-devices-show.yml

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        name: Check for Linting errors on MarkDown files
        files: readme.md
        args:
          - --fix
